# Generated by Django 5.0.6 on 2024-06-23 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='create',
        ),
        migrations.AddField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
