# Generated by Django 5.0.6 on 2024-06-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_create_task_created_at_task_modified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]
